.script/setup.sh
application/base.go
application/encoding.go
application/initialize/collectGenesisTransactionsCommand.go
application/initialize/genesisTransactionCommand.go
application/sim_test.go

Ready for v0.1.0 release.

---

go.mod
go.sum

Fix bug with using custom channels.

Bumping tendermint version to 0.34.10.

---

.script/reset.sh
.script/setup.sh
Dockerfile
Makefile

- script and use variable nmenoic
- update `dockerfile` to remove final image
- remove app user in docker for faster testing
Run following command to build and test the fix
``` bash
make docker-build
make docker-run DOCKER_CMD="/bin/sh -c .script/setup.sh" DOCKER_OPTS="--rm -it"
```

Fix for #26, setup.sh to use reset

---

Makefile
contrib/local/README.md
contrib/local/gov_contract.sh
contrib/local/setup.sh
contrib/local/test_cw20_govinit.sh
contrib/local/upgrade.sh

Script Fixes inside contrib/local
Fixed the scripts to work for Mac

script fixes

---

docs/resources/TestnetContracts.md

Added the link for the Smart Contracts Over Governance from cosmwasm

Added links 

---

app/ante_handler.go
app/app.go
app/genesis.go
cmd/persistenceCore/cmd/genaccount.go
cmd/persistenceCore/cmd/root.go
cmd/persistenceCore/main.go
x/halving/abci.go
x/halving/keeper/keeper.go
x/halving/simulation/params.go
x/halving/types/expected_keepers.go
x/halving/types/params.go
x/halving/types/params_test.go

Refactor imports to small case for consistency with go paradigm

Refactor imports to be smallcase instead of camelcase

---

.github/workflows/lint.yml
.github/workflows/release.yml

- consistent naming and formatting for ymls
-renamed all ```yaml``` to``` yml```
just run the workflows.

consistent yml files

---

.github/workflows/release.yml
Makefile

Fix release docker image building
Additionally we will also build the release dir for every PR to master, to make sure that we can basically create a release at any point.

Try fix release creation

---

go.mod
go.sum

Depricate ibc v3.0.1 from v3.1.1

Depricate ibc to v3.0.1 from v3.1.1

---

contrib/local/Makefile

Set a version for cosmovisor, add GOBIN into the makefile, set if unset

---

contrib/local/configs/keys.json
contrib/local/configs/relayer-keys.json
contrib/local/configs/validators.json

Update addresses for test wallets as per the new cointype 118

update addresses as per new cointype

---

contrib/local/configs/keys.json
contrib/local/configs/relayer-keys.json
contrib/local/configs/validators.json

Reverts persistenceOne/persistenceCore#116

Revert "update addresses as per new cointype"

---

contrib/local/configs/keys.json
contrib/local/configs/relayer-keys.json
contrib/local/configs/validators.json

Replace: #116 
Update addresses for test wallets as per the new cointype 118

update test addresses

---

SECURITY.md

Have created the SECURITY.md file containing guidelines for reporting security-related bugs

Security policy for persistenceCore

---

docker/Makefile

Minor makefile fixes for docker

minor fixes for docker makefile

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/release.yml
README.md

- changes master to main with the branch renaming
- just refactor

change master to main

---

docker/persistencecore/Dockerfile
docker/persistencecore/Dockerfile.release

chore: update versions at Dockerfiles

---

README.md

Modify Prerequisites go 1.19.3+ version

Modify Prerequisites go version

---

app/app.go

Comment out store creation on upgrade

---

app/upgrades/v6/cos_patch.go
app/upgrades/v6/records.go

Add tombstone data for minting tokens to addresses and validator address for untombstoning

Add records and validator information

---

app/ante_handler.go
app/app.go
app/expected_keeper.go
app/keepers/keepers.go
app/keepers/keys.go
app/keepers/modules.go
app/modules.go
app/upgrades/v8/constants.go
contrib/local/Makefile
contrib/local/README.md
contrib/local/oracle/contract.sh
contrib/local/oracle/feeder.sh
contrib/local/oracle/proposal.json
contrib/local/oracle/update_params.sh
go.mod
scripts/setup.sh
wasmbindings/query_plugin.go
wasmbindings/stargate_whitelisted_queries.go
wasmbindings/wasm.go

Check #179 & #186 for description

Integration of oracle module

---

app/encoding.go

add sdk encoders

---

app/app.go
app/encoding.go
app/genesis.go
app/keepers/keepers.go
app/modules.go
app/sim_test.go
app/upgrades/types.go
app/upgrades/v7/constants.go
app/upgrades/v7/upgrades.go
app/upgrades/v8/constants.go
app/upgrades/v8/upgrades.go
cmd/persistenceCore/cmd/root.go
cmd/persistenceCore/main.go
go.mod

prepare v8

---

app/app.go
app/upgrades/v9.1.0/constants.go
app/upgrades/v9.1.0/upgrades.go
interchaintest/chain_upgrade_test.go

Add `v9.1.0` with no migrations.

chore: register v9.1.0 upgrade and update the test

---

go.mod
go.sum

pstake registers new MsgLiquidStakeLSM into amino registry for ledger signing

fix!: update pstake mods.

---

go.mod
go.sum

related https://github.com/lum-network/chain/pull/61, https://github.com/cosmos/cosmos-sdk/issues/18423

fix: update ledger-go versions

---

app/keepers/keepers.go
app/keepers/keys.go
app/keepers/modules.go
app/modules.go
go.mod
go.sum

bumps pstake version to 2.8, 
adds ratesync keeper, add it's hooks, add's it to ica stack.

feat: update pstake mod to 2.8.0 and add ratesync keeper

---

wasmbindings/stargate_whitelisted_queries.go

Fixing Stargate query path in whitelist.
Modifying Stargate query path in whitelist.
Query exchange rate from contract.
- [ x] Does the Readme need to be updated?
None
None

fix(stargate-whitelisted-query): Query exchange rate

---

wasmbindings/stargate_whitelisted_queries.go

Add more to Stargate query path in whitelist.
Add more to Stargate query path in whitelist.
Via contract or ibctest
- [ x] Does the Readme need to be updated?
None
None

chore(wasmbindings): Add more queries to stargate whitelist

---

app/app.go
app/upgrades/v10.4.1/constant.go
app/upgrades/v10.4.1/upgrades.go
interchaintest/chain_upgrade_test.go

add upgrade handler for v10.4.1

add upgrade handler for 10.4.1

---

app/upgrades/v11.8.0/upgrades.go

just comments a back referenced PR as a potential fix.

chore: comment fix for v11 upgrade mainnet.

---

Makefile
proto/buf.lock
proto/scripts/proto-swagger-gen.sh

Build swagger docs using proto-builder image

fix: swagger gen using proto-builder image

---

app/app.go
app/upgrades/v11.10.0/constants.go
app/upgrades/v11.10.0/upgrades.go
interchaintest/chain_upgrade_test.go

adds upgrade name for mainnet.

prepare mainnet v11.10.0

---

app/app.go
app/upgrades/v11.13.0/constants.go
app/upgrades/v11.13.0/upgrades.go
go.mod
go.sum
interchaintest/chain_upgrade_test.go

chore: prepare mainnet v11.13.0

---

docs/resources/Ledger.md
interchaintest/module_pfm_test.go

chore: fix some comments

---

app/app.go
app/keepers/keepers.go
app/upgrades/testnet/v11.14.0-rc0/README.md
app/upgrades/testnet/v11.15.0-rc0/constants.go
app/upgrades/testnet/v11.15.0-rc0/upgrades.go
interchaintest/chain_upgrade_test.go
interchaintest/module_pfm_test.go

- Vesting accounts fix for LSM ( as no vesting accounts are currently under vesting, we will just convert them to base accounts )
- ibc transfer stack rearrange to fix ibchooks no being called during send packet

feat: prepare v11.15.0-rc0

---

docker/persistencecore/Dockerfile
docker/persistencecore/Dockerfile.release

use correct wasmvm version while building docker image

---

app/upgrades/testnet/v12.0.0-rc0/upgrades.go

re-add stk-assets redeem functionality to v12 upgrades

feat: add redeem stkassets to v12

---

app/app.go
app/upgrades/v12.0.0/constants.go
app/upgrades/v12.0.0/upgrades.go
go.mod
go.sum
interchaintest/chain_upgrade_test.go

adds upgrade instructions and dep updates

chore: prepare v12.0.0

---

README.md
docker/persistencecore/Dockerfile
docker/persistencecore/Dockerfile.release

fix release - udpate go docker verisons

fix: update go versions
