persistenceOne/persistenceCore

Dockerfile
Makefile

- `Dockerfile` to build `persistenceCore` from source and results into a final light weight image with binary.
- Added supported make commands for building and test running the container, makefile has instructions in comments.
Inorder to run quickly, run
```
make docker-build
make docker-interactive
make docker-clean
```
For long term processes, it is recommend to use docker commands directly for now.

Add Dockerfile and supporting commands for running docker

---

app/app.go
app/constants.go
contrib/local/Makefile
contrib/local/gov_contract.sh
contrib/local/setup.sh
contrib/local/upgrade.sh
go.mod
go.sum

Add permissioned wasm module and set update store loader.
* Create `initParamsKeeper` function
* Set wasm params so that it can not be stored directly, but via proposals
* Build binary with `make build`
* `cd contrib/local`
* Run `make`, this will start a new chain and run it
* In a seperate terminal run `make run-gov-upgrade`, this will test submitting a contract via a proposal, then instantiate the contract and run some sample execution command on them.
* After running the chain with a previous version binary
* Run `make run-upgrade`
* Currently this upgrade is not actually working since testing a software upgrade from `v0.2.3` does not seem to work
* The implementation for wasm does not seem to be the problem, since software upgrade actually works from commit `9bf5dde`
* Debug refactor …

Add subspce function and init params keeper

---

.dockerignore
.gitignore
Dockerfile
Makefile
contrib/local/Makefile
contrib/local/README.md
contrib/local/setup.sh

Add docker based testing for persistence chain in `contrib/local`. Create statically linked go binaries with libwasm.
* Create dockerfile of persistenceCore with statically (with libwasm) created binary for persisteceCore
* Push docker image `persistenceone/persistencecore:latest` with `contrib/local` scripts
* Add docker setup and exec commands for interactions with persistenceCore and wasm in `contrib/local`
* `cd contrib/local`
* `make docker-setup`: This will pull the docker image and start the container and run the full setup, run the docker container in the background
* `make docker-exec`: Open bash script into the container. Then can run `make run-gov-contract` commands from within the container.
* Run `make docker-clean` to stop the running container
* This does not have upgrade …

Add docker based wasm testing scripts

---

contrib/local/setup.sh

Make setup of local chain more effective with setting `.persisiteceCore/config/client.toml` for handier usage.

Add settings for local setup in client.toml

---

Makefile

-->
Makefile will use tags if possible else use branch-commit format for version.
its mostly a fix for existing checks
`persistenceCore version`
`persistenceCore version`

chore: version fix and trimpath

---

cmd/persistenceCore/cmd/root.go

keys failed to create with --home flag
read persistent flags  in cmd/root.go main command.
```
persistenceCore keys delete  testkey --keyring-backend test --home .xyz -y
persistenceCore keys add testkey --keyring-backend test --home .xyz
```

fix: read persistent command flags.

---

go.mod
go.sum

updates persistence-sdk and pstake-native to 1.0.0 tags.

update persistence-sdk, pstake-native to stable 1.0.0.

---

go.mod
go.sum

Fixes pstake rest queries
- bump go.mod to use correct gomod version.
- rest.core.persistence.one/pstake/lscosmos/v1beta1/c_value

add rest queries for pstake.

---

contrib/local/setup.sh

Currently `pstake`, `restake`, `unstake` words are being changed to `puxprt`, `reuxprt`, `unuxprt` due to the denom changing sed.
Protected above words for the replacement.
Init local chain.

fix local chain init

---

app/app.go

- adds upgrade/fork instructions for pstake. (resetting c_value to 1), and distributing tokens w.r.t those.
- calculates diff between already staked atoms and minted supply, mints the diff, distributed the diff to sender acc and fee address.
- by upgrade testing

add pstake upgrade instructions.

---

go.mod
go.sum

version bump
- persistence-sdk v2.0.0
- pstake-native v2.0.0

bump v2.0.0 of persistence-sdk and pstake-native

---

app/upgrades/v8/upgrades.go

Setting oracle `acceptList` empty to give validators time to setup oracle initially. And later add pairs to `acceptList` via proposal.

set oracle accept list empty

---

app/app.go
go.mod
go.sum

Adds an in-place state migration to fix the cons fail on the testnet, will prevent math failing on nil fields.
Related: https://github.com/persistenceOne/persistence-sdk/pull/397

fix: adds missing migration for LS validator fields in the testnet.

---

docker/persistencecore/Dockerfile
docker/persistencecore/Dockerfile.release
go.mod
go.sum

Upgraded `wasmvm` to `1.1.2` - security patch for [CWA-2023-002](https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2023-002.md)

CosmWasm cherry security patch

---

app/keepers/keepers.go

reverts an accidental change made in https://github.com/persistenceOne/persistenceCore/commit/660d643d5e84f1e1b5cc7644144ff50497c9d4ee
fixes issue with statesync:
```
> failed to restore snapshot err="extension wasm restore: processing snapshot item: Error calling the VM: Error during static Wasm validation: Wasm contract requires unavailable capabilities: {\"staking\"}: create wasm contract failed"
```

fix: don't remove staking from wasm supportedFeatures

---

app/app.go
app/upgrades/v8rc4/constants.go
app/upgrades/v8rc4/upgrades.go
go.mod
go.sum

Bumps persistence-sdk https://github.com/persistenceOne/persistence-sdk/releases/tag/v2.1.0-rc3 
has breaking consensus changes, needs testnet upgrade

chore: bump persistence-sdk to v2.1.0-rc3

---

go.mod
go.sum

Rolling update for huckleberry security advisory: https://github.com/cosmos/ibc-go/releases/tag/v4.3.1
See also `persistence-sdk` v2.0.1 https://github.com/persistenceOne/persistence-sdk/releases/tag/v2.0.1

chore: update ibc-go dep to v4.3.1

---

CHANGELOG.md
app/ante_handler.go
app/app.go
app/keepers/keepers.go
app/keepers/keys.go
app/keepers/modules.go
app/modules.go
app/upgrades/v8/constants.go
app/upgrades/v8/upgrades.go
go.mod
go.sum

Add POB module for skip MEV
- Includes Auction mempool and their custom Ante decorator from v1.0.0
- Disables Auction by setting `MaxBundleSize` to`0` in upgrade handler (to be enabled later)

feat: add POB module for skip-mev

---

CHANGELOG.md
app/upgrades/v8/upgrades.go

Set minimum limit for `CommissionRate` to 5 and `MaxCommissionRate` to 10
**NOTE:** Setting `MaxCommissionRate` to 10 instead of 5 to give validators some margin to work with.

fix(commission): enforce min limits for rate & maxRate

---

Makefile
chains.yaml

Refactor `Makefile` to be aligned with rest cosmos projects, most importantly:
* fix static build when doing `make install`, some linking args (LDFLAGS) were eaten
* remove unused commands, especially under "Documentation" section, those don't belong to Documentation anyway.
* added linting commands, similar to upstream cosmos sdk
* fixing the static build was needed to facilitate building using common pipelines such as [Heighliner](https://github.com/strangelove-ventures/heighliner)
Also adds a config for **Heighliner** and corresponding makefile commands.
TODO: future improvements to Makefile should include sims running

Refactor Makefile build flags and add Heighliner config

---

app/keepers/keepers.go

Removed ibcfee from ica controller stack.
This caused failure in ICA channel creation, where channel version was sent with `{"fee_version":"ics29-1"}`.
the error log from relayer
> rpc error: code = Unknown desc = rpc error: code = Unknown desc = failed to execute message; message index: 1: channel open try callback failed: cannot unmarshal ICS-27 interchain accounts metadata: unknown data type [cosmos/ibc-go/v4@v4.2.0/modules/apps/27-interchain-accounts/host/keeper/handshake.go:39] With gas wanted: '0' and gas used: '147268' : unknown request

fix: remove ibcfee from ica controller stack

---

.github/workflows/e2e-testing.yaml

This is a CI workflow `End to End Tests` that creates a test matrix for interchaintest suite. It replaces workflow `E2E Upgrade tests` that used Starship and therefore disabled.
1. Implement YAML config that builds local branch docker image and submits as an artefact to the next stage
2. The next stage performs steps - 1 per each `ictest-*` makefile action
NOTE:  `E2E Upgrade tests` has been manually disabled in the settings of this repo. The starship version can be run locally using [act](https://github.com/nektos/act)
This runs automatically on every PR.

Add E2E testing using interchaintest into CI

---

.github/workflows/e2e-testing.yaml

Trying to fix E2E CI for `main` branch when PR is merged and git ref is missing for some reason.
Also added `magnetikonline/action-golang-cache@v4` as a way to pre-cache go mods for the pipeline

fix: CI action E2E for main branch. Also pre-cache Go modules

---

CHANGELOG.md
app/upgrades/v8/upgrades.go
starship/v7v8/params.go

Sets initial LSM params
- `ValidatorBondFactor` to `250`
- `GlobalLiquidStakingCap` to `10%`
- `ValidatorLiquidStakingCap` to `50%`

set LSM params

---

Makefile
docker/Makefile
docker/persistencecore/Dockerfile
docker/persistencecore/Dockerfile.release

Release builds fails due to makefile changes. This fix quickly unblocks the flow, while planned revision of makefiles and dockerfiles in this repo is planned for the next sprint.

fix: quickfix for build release stage - bin paths and static linking

---

wasmbindings/stargate_whitelisted_queries.go

Added more queries to whitelist to allow querying gov module and pstake exchange rate from Cosmwasm Smart Contracts
Just added more queries to existing stargate whitelist
Stargate query for Gov Proposal / Params and Pstake exchange rate from a contract should work. Tried with a Dexter contract on localnet.
No.

add whitelist for governance and pstake stargate queries

---

go.mod
go.sum

Incorporates pStake bugfixes from 
https://github.com/persistenceOne/pstake-native/releases/tag/v2.3.2
https://github.com/persistenceOne/pstake-native/releases/tag/v2.3.1

fix: pstake-native bumped to v2.3.2

---

app/app.go
app/upgrades/v9.2.0/constants.go
app/upgrades/v9.2.0/upgrades.go
interchaintest/chain_upgrade_test.go

Creates upgrade handler for v9.2.0, removes v9.1.0, v9 from upgrade handler as no longer required.
to be reviewed/ merged post #239

chore: create upgrade handler for v9.2.0

---

app/modules.go

Genesis export was failing:
```
panic: module consensus does not exist
goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/types/module.(*Manager).ExportGenesisForModules(_, {{0x3463b60, 0x4b91ba0}, {0x34798e0, 0xc00c0b0080}, {{0x0, 0x0}, {0x0, 0x0}, 0xca6170, ...}, ...}, ...)
github.com/cosmos/cosmos-sdk@v0.47.3/types/module/module.go:393 +0x4df
github.com/persistenceOne/persistenceCore/v9/app.(*Application).ExportAppStateAndValidators(0xc0005df2d0, 0x0, {0x4b91ba0, 0x0, 0x0}, {0x4b91ba0, 0x0, 0x0})
github.com/persistenceOne/persistenceCore/v9/app/export.go:25 +0x1e7
```

fix: don't use consensus module in genesis import/export for now

---

app/keepers/keepers.go

Increased max limit for proposal metadata length.

increase metadata length limit to 5000

---

app/upgrades/v10/constants.go
app/upgrades/v10/upgrades.go

Reduce block size as per https://forum.cosmos.network/t/amulet-security-advisory-for-cometbft-asa-2023-002/11604/1
Currently it reduces by half to ~5mb, recommended is 2mb
Creating a PR so that it does not fall through the cracks. 
add upgrade handler of v10
- have not changed the app imports to v10 as it is not necessary as of now, that can be done when v10 is fully planned.

add v10 upgrade to reduce blocksize

---

go.mod
go.sum

chore: update pstake to 2.5.1

---

go.mod
go.sum

https://github.com/persistenceOne/ibc-apps/releases
Includes this fix:
https://github.com/persistenceOne/ibc-apps/commit/7c8f814d3b79cd05abb437f8a4362c2763affcc0
e2e tests work within pfm middleware in ibc-apps

Bump ibc-apps to v7.2.0-lsm6 which contains a fix for pfm

---

go.mod
go.sum
interchaintest/go.mod
interchaintest/go.sum

Adds version bump 
https://github.com/persistenceOne/pstake-native/releases/tag/v2.8.2

bump pstake-native to v2.8.2

---

app/app.go
app/upgrades/testnet/v11.13.0-rc0/constants.go
app/upgrades/testnet/v11.13.0-rc0/upgrades.go
go.mod
go.sum
interchaintest/chain_upgrade_test.go
interchaintest/liquidstake_stkxprt_globalcap_test.go
interchaintest/liquidstake_stkxprt_test.go

Updates pstake version to v2.15.0-rc1 https://github.com/persistenceOne/pstake-native/releases/tag/v2.15.0-rc0

chore: prepare v11.13.0-rc0 for testnet

---

app/app.go
app/upgrades/v11.14.0/constants.go
app/upgrades/v11.14.0/upgrades.go
app/upgrades/v11.14.0/upgrades_test.go
interchaintest/chain_upgrade_test.go

ref: https://github.com/persistenceOne/pstake-native/issues/853

chore: prepare v11.14.0

---

app/app.go
app/upgrades/v11.16.0/constants.go
app/upgrades/v11.16.0/upgrades.go
app/upgrades/v11.16.0/upgrades_test.go
interchaintest/chain_upgrade_test.go

fixes: https://github.com/persistenceOne/pstake-native/issues/853, for two more unbondings

chore: prepare v11.16.0

---

.github/workflows/build.yml
.github/workflows/e2e-testing.yaml
Makefile
README.md
docker/persistencecore/Dockerfile
docker/persistencecore/Dockerfile.release
interchaintest/go.mod

fix go versions in CI/ dockers for release

fix: update go version in dockers and CI

---

app/upgrades/v11.20.0/README.md
go.mod
go.sum

mod updates fix:  https://github.com/cosmos/ibc-go/security/advisories/GHSA-4wf3-5qj9-368v and https://github.com/cosmos/cosmos-sdk/security/advisories/GHSA-47ww-ff84-4jrg

chore: update sdk/ ibc-go version with latest fixes

---

app/upgrades/v13.0.0/upgrades.go

udpate halving params on mainnet upgrade instrucitons

chore: update v13 mainnet upgrade instructions
